# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-pre-commit-buildkite-plugin
  description: Buildkite Pipeline for pre-commit-buildkite-plugin
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/pre-commit-buildkite-plugin

spec:
  type: buildkite-pipeline
  owner: group:release-eng
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: pre-commit-buildkite-plugin
      description: Buildkite plugin to run https://pre-commit.com
    spec:
      repository: elastic/pre-commit-buildkite-plugin
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        release-eng:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
