---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "Pre-commit"
    command: "hooks/post-checkout"
    plugins:
      - elastic/hermit#v1.0.1
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential:latest@sha256:923bde2b5cced21dc9694119a5bd142789ba77146a0f813212c4cebd96971151"
  - label: ":sparkles: Buildkite plugin Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: elastic/pre-commit
    agents:
      provider: "gcp"
      image: family/core-ubuntu-2204
