---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "Pre-commit"
    command: "hooks/post-checkout"
    plugins:
      - elastic/hermit#v1.0.0
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
  - label: ":sparkles: Buildkite plugin Lint"
    plugins:
      - plugin-linter#v3.0.0:
          id: elastic/pre-commit
    agents:
      provider: "gcp"
      image: family/ci-ubuntu-2204
